### ISSUE TITLE
opsdroid service yaml doesnt have a apiVersion

### ISSUE THREAD

**Issue by abhiky** [opsdroid/helm-chart#1]
```
kind: Service
metadata:
  name: opsdroid
spec:
  ports:
    - port: {{ .Values.opsdroid.service.port }}
      targetPort: {{ .Values.opsdroid.service.port }}
      protocol: TCP
  selector:
    app: opsdroid
````
needs to be 

```
apiVersion: v1
kind: Service
metadata:
  name: opsdroid
spec:
  ports:
    - port: {{ .Values.opsdroid.service.port }}
      targetPort: {{ .Values.opsdroid.service.port }}
      protocol: TCP
  selector:
    app: opsdroid
```
